---
test-cases:
  - summary: |
      Окно поиска
    status: fail

bugreports:
  - summary: |
      Не работает поиск товаров по первым буквам
    environment: |
      Google Chrome   Версия 109.0.5414.120 (Официальная сборка), (64 бит)
      ОС Microsoft Windows 7 Версия 6.1.7601 Service Pack 1 Сборка 7601
   steps-to-reproduce: |
      1. Зайти на сайт: https://hexlet-products-store.vercel.app/
      2. Перейти в окно поиска
      3. Ввести первые буквы товара
   expected-result: |
      На странице каталога будут отображены товары название которых соответствует вводимым буквам
   actual-result: |
      На странице каталога отображаются другие товары

