---
- summary: |
    Страница магазина
  requirement: |
    Выводится список товаров на главной странице магазина
  prerequisites: |
    Открыта главная страница магазина
  test-data: |
    https://hexlet-products-store.vercel.app/
  steps:
    - Открыть сайт: https://hexlet-products-store.vercel.app/ 
  expected-result: |
    Пользователь должен попасть на главную страницу магазина

- summary: |
    Окно поиска
  requirement: |
    Проверка предложений в каталоге
  prerequisites:
    Открыта главная страница магазина
  test-data: |
    https://hexlet-products-store.vercel.app/
  steps:
    - Открыть сайт: https://hexlet-products-store.vercel.app/
    - Вводим буквы в окне поиска
  expected-result: |
    Все товары на главной странице начинаются с уже введенных букв

- summary: |
    Корзина
  requirement: |
    Удаление продукта из корзины
  prerequisites:
    Открыта главная страница магазина
  test-data: |
    https://hexlet-products-store.vercel.app/
  steps:
    - Перейти на сайт: https://hexlet-products-store.vercel.app/
    - Добавьте товары в “Корзину”
    - Нажмите на значок корзины
    - Нажмите кнопку “Удалить”
  expected-result: |
    Товар больше не отображается в корзине

